/* Generated by tools/build_fonts.sh — see tools/README.md for the source fonts,
 * their OFL licence and the subsetting decision.
 *
 * These are .rodata, and CONFIG_SPIRAM_RODATA=y relocates .rodata into PSRAM,
 * so every face here competes with the framebuffer for PSRAM bandwidth.
 * Total set: ~1.53 MiB. Measured in PLAN.md M1.
 */
#pragma once
#include "lvgl.h"

/* Hero ladder — auto-shrinks 100 -> 76 -> 56 rather than truncating a city name.
 * Subset WITHOUT Latin Extended-A; see tools/README.md for the byte cost. */
extern const lv_font_t plex_sans_cond_100;
extern const lv_font_t plex_sans_cond_76;
extern const lv_font_t plex_sans_cond_56;

/* Secondary hero and body */
extern const lv_font_t plex_sans_cond_34;
extern const lv_font_t plex_sans_cond_25;
extern const lv_font_t plex_sans_cond_22;

/* Numeric — IBM Plex Mono is tabular by default, which is why it is here:
 * lv_font_conv applies no OpenType features, so a `tnum`-only font would
 * render digits that visibly jitter every refresh. (DESIGN.md §3) */
extern const lv_font_t plex_mono_32;
extern const lv_font_t plex_mono_17;
extern const lv_font_t plex_mono_13;
extern const lv_font_t plex_mono_12;
